### ISSUE TITLE
Diamond blocks not being placed into botany pots

### ISSUE THREAD

**Issue by reaction** [WCDN-group/To-Creationist-Surrealist#1]
Just a few hours into the pack. When I try to right-click on a botany pot with a diamond block, it just disappears and is removed from my inventory. I can still place stone into the botany pot afterwards, and I can place a beacon in the pot, just not a diamond block.

**Comment by liuseniubi** [comment]
Can you give me your latest.log in the logs folder?

**Comment by reaction** [comment]
[latest.log](https://github.com/liuseniubi/CreaTech/files/6269183/latest.log)

**Comment by liuseniubi** [comment]
Okay, I saw the problem and I reproduced this, I'll fix it later.

**Comment by liuseniubi** [comment]
Fixed! Thanks!
