### ISSUE TITLE
Sixcolium nugget crashing game

### ISSUE THREAD

**Issue by BreadtheRipper** [WCDN-group/To-Creationist-Surrealist#5]
I am on version 1.07 of the pack
When attempting to create the sixcolium nugget, the game crashes completely
Upon restart, the game gives me back the ingot, and if I try to create the nugget again, it just crashes
I have attached the latest crash report
[crash-2021-05-08_22.25.10-client.txt](https://github.com/liuseniubi/CreaTech/files/6446849/crash-2021-05-08_22.25.10-client.txt)

**Comment by liuseniubi** [comment]
Update the modpack pls.

**Comment by BreadtheRipper** [comment]
Correction, it's version 1.07 of the pack, I made a typo. To my knowledge, this is the latest version that is available on curse forge, unless I'm missing something?

**Comment by liuseniubi** [comment]
Just delete the Fast Workbench mod, I remembered that I've deleted before, but it still here, so weird.
